### ISSUE TITLE
Hide SideBar 

### ISSUE THREAD

**Issue by Cristian-Ayala** [Cristian-Ayala/acosta-repuesto-vue#5]
When collapsing the sidebar, instead of just shrinking, hide it. It will give us more space. 

This should be the default sidebar size:
![1](https://user-images.githubusercontent.com/41448429/117878763-53a8a600-b263-11eb-95fd-01329d0f0172.png)

This should look like when clicking the button:
![2](https://user-images.githubusercontent.com/41448429/117878765-54413c80-b263-11eb-8426-b8b62e2cc27d.png)

**Comment by quikemo** [comment]
mmm lo veo dificil jajaja
